const blog_data = [
    {
      id: 1,
      img: "/images/blog/blog_img_04.jpg",
      icon: "/images/blog/logo_07.png",
      tag: "Solution",
      featured: "Featured",
      date: "18 Jul 2022",
      title: " Print, publishing qui visual ux layout mockups.",
      blog_1: true,
    },
    {
      id: 2,
      img: "/images/blog/blog_img_04.jpg",
      icon: "/images/blog/logo_07.png",
      tag: "Solution",
      featured: "Featured",
      date: "22 Jul 2022",
      title: " Designer’s Checklist for Every UX/UI Project.",
      blog_1: true,
    },
    {
      id: 3,
      img: "/images/blog/blog_img_04.jpg",
      icon: "/images/blog/logo_07.png",
      tag: "Solution",
      featured: "Featured",
      date: "18 Jul 2022",
      title: "Make more productive working flow daily.",
      blog_1: true,
    },
    {
      id: 4,
      img: "/images/blog/blog_img_04.jpg",
      icon: "/images/blog/logo_07.png",
      tag: " Solution, Design",
      featured: "Featured",
      date: "22 Jul 2022",
      title: "Print, publishing qui visual ux layout mockups.",
      blog_1: true,
    },
    {
      id: 5,
      img: "/images/blog/blog_img_04.jpg",
      icon: "/images/blog/logo_07.png",
      tag: "Solution",
      featured: "Featured",
      date: "18 Jul 2022",
      title:
        "Medieval origins to the digital era, learn everything there is to know.",
      blog_1: true,
    },
    {
      id: 6,
      img: "/images/blog/blog_img_04.jpg",
      icon: "/images/blog/logo_07.png",
      tag: " Solution, Design",
      featured: "Featured",
      date: "22 Jul 2022",
      title: "Print, publishing qui visual ux layout mockups.",
      blog_1: true,
    },
  
    {
      id: 7,
      img: "/images/blog/blog_img_04.jpg",
      classStyle: "",
      blog_1: true,
      tag: "Solution",
      featured: "Featured",
      date: "22 Jul 2022",
      title: " Print, publishing qui visual ux layout mockups.",
    },
    {
      id: 8,
      img: "/images/blog/blog_img_04.jpg",
      classStyle: "",
      blog_1: true,
      tag: "Solution",
      featured: "Featured",
      date: "22 Jul 2022",
      title: " Designer’s Checklist for Every UX/UI Project.",
    },
    {
      id: 9,
      img: "/images/blog/blog_img_04.jpg",
      classStyle: "text-style",
      blog_1: true,
      tag: "Solution",
      featured: "Featured",
      date: "22 Jul 2022",
      title: "Make more productive working flow daily.",
    },
    {
      id: 10,
      img: "/images/blog/blog_img_04.jpg",
      classStyle: "",
      blog_1: true,
      tag: "Solution",
      featured: "Featured",
      date: "22 Jul 2022",
      title: "Make more productive working flow daily.",
    },
    {
      id: 11,
      img: "/images/blog/blog_img_04.jpg",
      classStyle: "",
      blog_1: true,
      tag: "Solution",
      featured: "Featured",
      date: "22 Jul 2022",
      title: "Print, publishing qui visual ux layout mockups.",
    },
  
    // blog 2
    {
      id: 12,
      img: "/images/blog/blog_img_04.jpg",
      tag: "Solution",
      title: " Print, publishing qui visual ux layout mockups.",
      blog_1: true,
    },
    {
      id: 13,
      img: "/images/blog/blog_img_04.jpg",
      tag: "Solution",
      title: " Designer’s Checklist for Every UX/UI Project.",
      blog_1: true,
    },
    {
      id: 14,
      img: "/images/blog/blog_img_04.jpg",
      tag: "Solution",
      title: "Make more productive working flow daily.",
      blog_1: true,
    },
    {
      id: 15,
      img: "/images/blog/blog_img_04.jpg",
      tag: "Solution",
      title: "Print, publishing qui visual ux layout mockups.",
      blog_1: true,
    },
  ];
  
  export default blog_data;
  